services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: azship
      POSTGRES_DB: fretes
      POSTGRES_USER: azship
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U azship -d fretes"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fretes
      SPRING_DATASOURCE_USERNAME: azship
      SPRING_DATASOURCE_PASSWORD: azship
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
